#!/usr/bin/env node
// Builds content/reading.js: the text of every chapter in each week's
// reading block (the `reference` in content/weeks.js, like "Isaiah 40–49"
// or "Isaiah 13–14; 22; 24–30; 35"), so he can read the chapters themselves
// in the app. Same pinned public-domain data as tools/verify.mjs. Then the
// same chapters in the Berean Standard Bible (content/bsb.js), the
// Reina-Valera 1909 (content/es.js) and the 1905 Ang Biblia (content/tl.js).
//
// The deploy runs this after the content check, so a week added from
// developer mode gets its chapters with no extra step. The file isn't kept
// in git. To try the reader locally: node tools/verify.mjs once (it
// downloads the data), then  node tools/build-reading.mjs
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';
import { loadOriginal, langOf } from './original.mjs';
import { loadLexicon, loadGrammar, loadUses, kidGrammar, wordFile, strongKey } from './words.mjs';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const CACHE = process.env.SCRIPTURE_CACHE || path.join(ROOT, 'tools', '.scripture-cache');
const VOLUMES = ['old-testament', 'new-testament', 'book-of-mormon', 'doctrine-and-covenants', 'pearl-of-great-price'];

const files = fs.existsSync(CACHE) ? fs.readdirSync(CACHE) : [];
const chapters = new Map();   // "Isaiah 40" -> ["Comfort ye, …", …] (verse 1 first)
for (const name of VOLUMES) {
  const f = files.find(x => x.endsWith('-' + name + '.json'));
  if (!f) throw new Error('Run node tools/verify.mjs once first, to download the scripture data');
  const data = JSON.parse(fs.readFileSync(path.join(CACHE, f), 'utf8'));
  for (const c of data.sections || data.books.flatMap(b => b.chapters)) {
    for (const v of c.verses) {
      const key = v.reference.replace(/:\d+$/, '');
      if (!chapters.has(key)) chapters.set(key, []);
      chapters.get(key)[v.verse - 1] = v.text;
    }
  }
}

// Names the lesson pages use that the data spells another way.
const ALIAS = { 'Song of Solomon': "Solomon's Song", 'Solomon’s Song': "Solomon's Song", 'Psalm': 'Psalms', 'D&C': 'Doctrine and Covenants' };
const lookup = ch => { const m = /^(.+) (\d+)$/.exec(ch); return chapters.get((ALIAS[m[1]] || m[1]) + ' ' + m[2]); };

// "Ezra 1; 3–7; Nehemiah 2; 4–6" -> ["Ezra 1", "Ezra 3", …, "Nehemiah 6"].
// A part with verses ("Genesis 5:21–24") still brings its whole chapter, and
// a book on its own ("Hosea 1–6; Joel") brings every chapter of it.
// The app reads the block the same way (readingUnits in index.html).
function blockChapters(reference) {
  const out = [];
  let book = null;
  for (const raw of String(reference || '').split(';')) {
    const part = raw.trim();
    if (/^\d? ?[A-Za-z][^\d]*$/.test(part)) {            // a whole book
      book = part;
      for (let c = 1; lookup(book + ' ' + c); c++) out.push(book + ' ' + c);
      continue;
    }
    const m = /^(?:(.*?[A-Za-z].*?) )?(\d+)(?::\d+(?:[–-]\d+)?)?(?:[–-](\d+))?$/.exec(part);
    if (!m) throw new Error(`Can't read the reading block "${reference}" (at "${part}")`);
    if (m[1]) book = m[1];
    if (!book) throw new Error(`The reading block "${reference}" must start with a book`);
    const to = /:/.test(part) ? Number(m[2]) : Number(m[3] || m[2]);
    for (let c = Number(m[2]); c <= to; c++) out.push(book + ' ' + c);
  }
  return out;
}

const src = fs.readFileSync(path.join(ROOT, 'content', 'weeks.js'), 'utf8');
const MARK = 'window.TU_WEEKS = ';
const weeks = JSON.parse(src.slice(src.indexOf(MARK) + MARK.length, src.lastIndexOf(';')));

// A chapter it can't find is a warning, not a failure: the app then sends
// him to Gospel Library for it, so it never blocks a deploy.
const out = {};
let missing = 0;
for (const w of weeks) {
  let list = [];
  try { list = blockChapters(w.reference); } catch (e) { console.warn('⚠', w.dates + ':', e.message); missing++; }
  for (const ch of list) {
    const verses = lookup(ch);
    if (verses) out[ch] = verses;
    else { console.warn(`⚠ ${w.dates}: "${ch}" (from "${w.reference}") isn't in the scripture data`); missing++; }
  }
}
fs.writeFileSync(path.join(ROOT, 'content', 'reading.js'),
  '// Generated by tools/build-reading.mjs at deploy: the chapters of each week\'s reading.\n' +
  '// Do not edit by hand.\n' +
  'window.TU_READING = ' + JSON.stringify(out) + ';\n');
console.log(`content/reading.js: ${Object.keys(out).length} chapters` + (missing ? `, ${missing} not found (read in Gospel Library)` : ''));

// The weeks moved to content/past/ (tools/archive-weeks.mjs): each one's
// chapters in its own file, content/past/reading-<num>.js, which the app
// loads only when Past weeks opens that week. Not kept in git either.
const PAST = path.join(ROOT, 'content', 'past');
const pastIndex = (() => {
  const f = path.join(PAST, 'index.js');
  if (!fs.existsSync(f)) return [];
  const w = {};
  new Function('window', fs.readFileSync(f, 'utf8'))(w);
  return w.TU_PAST_INDEX || [];
})();
let pastCount = 0;
const pastChapters = [];
for (const p of pastIndex) {
  const text = {};
  let list = [];
  try { list = blockChapters(p.reference); } catch (e) { console.warn('⚠', p.dates + ':', e.message); }
  pastChapters.push(...list);
  for (const ch of list) {
    const verses = lookup(ch);
    if (verses) text[ch] = verses;
    else console.warn(`⚠ ${p.dates}: "${ch}" (from "${p.reference}") isn't in the scripture data`);
  }
  fs.writeFileSync(path.join(PAST, `reading-${p.num}.js`),
    `// Generated by tools/build-reading.mjs at deploy: the chapters of ${p.title} (${p.dates}).\n` +
    '// Do not edit by hand.\n' +
    `(window.TU_PAST_READING = window.TU_PAST_READING || {})[${p.num}] = ${JSON.stringify(text)};\n`);
  pastCount += Object.keys(text).length;
}
if (pastIndex.length) console.log(`content/past/: the chapters of ${pastIndex.length} past ${pastIndex.length === 1 ? 'week' : 'weeks'} (${pastCount})`);

// The same chapters in the Berean Standard Bible, for the BSB button in the
// reader: content/bsb.js, and content/past/bsb-<num>.js for past weeks, each
// loaded only when he turns the BSB on. From tools/bsb.txt.gz, the BSB's own
// text file (bereanbible.com/bsb.txt, 2026-09-28), which its header says
// "has been dedicated to the public domain". Kept in the repo, so the words
// never change under us; its books and verses line up with the KJV's.
// And the same for the reader's ES·TL button (Blake, 2026-10-03: "Using the
// Spanish and Tagalog bible sounds great where we can!"): the Reina-Valera
// 1909 (content/es.js, content/past/es-<num>.js) and the 1905 Ang Biblia
// (content/tl.js, content/past/tl-<num>.js), both public domain, from
// tools/rv1909.txt.gz and tools/tagalog1905.txt.gz, which
// tools/import-bibles.mjs made with each verse under the KJV verse it
// translates. A KJV verse the Spanish has no sure match for has none.
const BSB_BOOK = { 'Psalms': 'Psalm', 'Psalm': 'Psalm', "Solomon's Song": 'Song of Solomon', 'Solomon’s Song': 'Song of Solomon', 'Song of Solomon': 'Song of Solomon' };
const TRANSLATIONS = [
  { key: 'bsb', lib: 'b', file: 'bsb.txt.gz', name: 'the Berean Standard Bible (public domain)', g: 'TU_BSB', pg: 'TU_PAST_BSB', book: b => BSB_BOOK[b] || b },
  { key: 'es', lib: 'es', file: 'rv1909.txt.gz', name: 'the Reina-Valera 1909 (public domain)', g: 'TU_ES', pg: 'TU_PAST_ES', book: b => ALIAS[b] || b },
  { key: 'tl', lib: 'tl', file: 'tagalog1905.txt.gz', name: 'the 1905 Ang Biblia (public domain)', g: 'TU_TL', pg: 'TU_PAST_TL', book: b => ALIAS[b] || b },
];
for (const t of TRANSLATIONS) {
  const f = path.join(ROOT, 'tools', t.file);
  t.text = new Map();   // "Isaiah 40" -> ["“Comfort, comfort My people,” …", …], under the KJV's verse numbers
  if (!fs.existsSync(f)) { console.warn(`⚠ tools/${t.file} is missing, so the reader has no ${t.key.toUpperCase()}`); continue; }
  for (const line of zlib.gunzipSync(fs.readFileSync(f)).toString('utf8').split('\n')) {
    const [ref, x] = line.split('\t');
    const m = /^(.+) (\d+):(\d+)$/.exec((ref || '').trim());
    if (!m || !x) continue;
    const key = m[1] + ' ' + m[2];
    if (!t.text.has(key)) t.text.set(key, []);
    t.text.get(key)[Number(m[3]) - 1] = x.trim();
  }
  t.of = ch => { const m = /^(.+) (\d+)$/.exec(ch); return m && t.text.get(t.book(m[1]) + ' ' + m[2]); };
  // Only Bible chapters have them; a week in the Book of Mormon has none.
  const pick = list => Object.fromEntries(list.map(ch => [ch, t.of(ch)]).filter(([, v]) => v));
  const now = pick(Object.keys(out));
  fs.writeFileSync(path.join(ROOT, 'content', t.key + '.js'),
    `// Generated by tools/build-reading.mjs at deploy: the chapters of each week's reading in\n` +
    `// ${t.name}, from tools/${t.file}. Do not edit by hand.\n` +
    `window.${t.g} = ` + JSON.stringify(now) + ';\n');
  console.log(`content/${t.key}.js: ${Object.keys(now).length} chapters in ${t.name}`);
  for (const p of pastIndex) {
    let list = [];
    try { list = blockChapters(p.reference); } catch (e) { /* warned above */ }
    fs.writeFileSync(path.join(PAST, `${t.key}-${p.num}.js`),
      `// Generated by tools/build-reading.mjs at deploy: the chapters of ${p.title} (${p.dates}) in ${t.name}.\n` +
      '// Do not edit by hand.\n' +
      `(window.${t.pg} = window.${t.pg} || {})[${p.num}] = ${JSON.stringify(pick(list))};\n`);
  }
}

// The library, for the Scriptures tab (Blake, 2026-10-02: "add another tab
// where we can see our version of the scriptures. orgainzed by book,
// chapter, and verse"): content/library.js, every book of the five
// volumes with its chapter count, and content/lib/<chapter>.js, one file a
// chapter with its KJV verses (v) and, for a Bible chapter, its BSB (b),
// Spanish (es) and Tagalog (tl), loaded when he opens it. Not kept in git either.
const library = [];
{
  const NAMES = { 'old-testament': 'Old Testament', 'new-testament': 'New Testament', 'book-of-mormon': 'Book of Mormon', 'doctrine-and-covenants': 'Doctrine and Covenants', 'pearl-of-great-price': 'Pearl of Great Price' };
  const LIB = path.join(ROOT, 'content', 'lib');
  fs.rmSync(LIB, { recursive: true, force: true });
  fs.mkdirSync(LIB, { recursive: true });
  let n = 0;
  for (const vol of VOLUMES) {
    const data = JSON.parse(fs.readFileSync(path.join(CACHE, files.find(x => x.endsWith('-' + vol + '.json'))), 'utf8'));
    // The Doctrine and Covenants is sections ("D&C 4:2" in the data); the app calls them "Doctrine and Covenants 4".
    const books = data.books ? data.books.map(b => [b.book, b.chapters.length]) : [['Doctrine and Covenants', data.sections.length]];
    library.push({ name: NAMES[vol], books });
    for (const [book, count] of books) for (let c = 1; c <= count; c++) {
      const ch = book + ' ' + c, v = chapters.get((book === 'Doctrine and Covenants' ? 'D&C' : book) + ' ' + c);
      if (!v) { console.warn(`⚠ The library: ${ch} isn't in the scripture data`); continue; }
      const d = { v };
      if (/^(old|new)-testament$/.test(vol)) for (const t of TRANSLATIONS) { const x = t.text.get(t.book(book) + ' ' + c); if (x) d[t.lib] = x; }
      fs.writeFileSync(path.join(LIB, ch.toLowerCase().replace(/[^a-z0-9]+/g, '-') + '.js'),
        `// Generated by tools/build-reading.mjs at deploy: ${ch} (KJV${d.b ? ', and the BSB' : ''}${d.es ? ', the Reina-Valera 1909 and the 1905 Ang Biblia' : ''}). Do not edit by hand.\n` +
        `(window.TU_LIB = window.TU_LIB || {})[${JSON.stringify(ch)}] = ${JSON.stringify(d)};\n`);
      n++;
    }
  }
  fs.writeFileSync(path.join(ROOT, 'content', 'library.js'),
    '// Generated by tools/build-reading.mjs at deploy: the books of the five volumes and their chapters. Do not edit by hand.\n' +
    'window.TU_LIBRARY = ' + JSON.stringify(library) + ';\n');
  console.log(`content/library.js and content/lib/: ${library.reduce((a, v) => a + v.books.length, 0)} books, ${n} chapters`);
}

// The Hebrew and Greek, word by word, for the Hebrew and Greek button in the
// reader: content/original/<chapter>.js for every Bible chapter (this
// week's reading, the past weeks', and the rest for the Scriptures tab), each
// loaded only when he opens that chapter with the button on. From tools/original.mjs (STEPBible.org, from
// work at Tyndale House Cambridge, CC BY 4.0). Not kept in git either.
{
  const ORIG = path.join(ROOT, 'content', 'original');
  const slug = ch => ch.toLowerCase().replace(/[^a-z0-9]+/g, '-');      // the app's name for the file too
  try {
    // Every Bible chapter, for the Scriptures tab too.
    const bible = library.slice(0, 2).flatMap(v => v.books.flatMap(([book, count]) => Array.from({ length: count }, (_, i) => book + ' ' + (i + 1))));
    const orig = await loadOriginal(CACHE, [...new Set([...Object.keys(out), ...pastChapters, ...bible])].filter(langOf));
    fs.rmSync(ORIG, { recursive: true, force: true });
    fs.mkdirSync(ORIG, { recursive: true });
    // Each chapter carries its grammar codes in plain words (g: code -> [plain, full]) for the word study.
    const grammar = {};
    for (const lang of new Set([...orig.values()].map(d => d.lang))) {
      try { grammar[lang] = await loadGrammar(CACHE, lang); } catch (e) { console.warn('⚠ The grammar codes:', e.message); grammar[lang] = new Map(); }
    }
    for (const [ch, d] of orig) {
      d.g = {};
      for (const words of d.v) for (const w of words || []) {
        const full = w[4] && grammar[d.lang].get(w[4]);
        if (full && !d.g[w[4]]) d.g[w[4]] = [kidGrammar(full), full];
      }
      fs.writeFileSync(path.join(ORIG, slug(ch) + '.js'),
        `// Generated by tools/build-reading.mjs at deploy: ${ch} word by word, from STEPBible.org\n` +
        '// (Tyndale House Cambridge, CC BY 4.0). Do not edit by hand.\n' +
        `(window.TU_ORIG = window.TU_ORIG || {})[${JSON.stringify(ch)}] = ${JSON.stringify(d)};\n`);
    }
    console.log(`content/original/: ${orig.size} Bible chapters word by word, in Hebrew and Greek`);

    // The word study: one file per root word of the Bible, content/words/<number>.js
    // (h6960a.js): its dictionary entry, how many times the testament uses it,
    // the first verse and a spread of others with their KJV words, and up to
    // 250 of its verses with what it means in each. Loaded when he taps a word.
    const WORDS = path.join(ROOT, 'content', 'words');
    fs.rmSync(WORDS, { recursive: true, force: true });
    fs.mkdirSync(WORDS, { recursive: true });
    let written = 0, unknown = 0;
    for (const lang of new Set([...orig.values()].map(d => d.lang))) {
      const lex = await loadLexicon(CACHE, lang), uses = await loadUses(CACHE, lang);
      const kjv = ref => { const m = /^(.+) (\d+):(\d+)$/.exec(ref), vs = m && lookup(m[1] + ' ' + m[2]); return vs ? vs[Number(m[3]) - 1] || '' : ''; };
      const strongs = new Set();
      for (const d of orig.values()) if (d.lang === lang) for (const words of d.v) for (const w of words || []) if (w[3]) strongs.add(strongKey(w[3]));
      for (const strong of strongs) {
        const e = lex.get(strong) || lex.get(strong.replace(/[A-Z]$/, ''));
        if (!e) { unknown++; continue; }
        const all = uses.get(strong) || [], pick = [];
        if (all.length) pick.push(all[0]);
        for (let k = 1; k <= 7 && all.length > 1; k++) { const x = all[Math.round(k * (all.length - 1) / 7)]; if (!pick.includes(x)) pick.push(x); }
        const entry = { s: strong, lemma: e.lemma, sound: e.sound, gloss: e.gloss, def: e.def, n: all.length,
          some: pick.map(([ref, mean]) => [ref, mean, kjv(ref)]), uses: all.slice(0, 250) };
        fs.writeFileSync(path.join(WORDS, wordFile(strong)),
          `// Generated by tools/build-reading.mjs at deploy: ${strong}, from STEPBible.org (Tyndale House Cambridge, CC BY 4.0). Do not edit by hand.\n` +
          `(window.TU_WORDS = window.TU_WORDS || {})[${JSON.stringify(strong)}] = ${JSON.stringify(entry)};\n`);
        written++;
      }
    }
    console.log(`content/words/: ${written} word studies` + (unknown ? ` (${unknown} words with no dictionary entry)` : ''));
  } catch (e) { console.warn('⚠ The Hebrew and Greek words:', e.message, '(the reader goes without them)'); }
}

// The Church's own recordings of each chapter, a man's voice and a woman's,
// for the reader's Listen button (Blake, 2026-10-02, from the Scripture
// Central app): content/audio.js, a link to each MP3 on the Church's site,
// which the app plays from there. Looked up at deploy in the content Gospel
// Library itself loads. A chapter without one just has no Listen button.
// Not kept in git either.
{
  const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  const at = html.indexOf('const BOOK_PATHS = {'), end = html.indexOf('\n  };\n', at);
  const PATHS = new Function('return ' + html.slice(html.indexOf('{', at), end) + '}')();
  const want = [...new Set([...Object.keys(out), ...pastChapters])], queue = want.slice(), audio = {};
  await Promise.all(Array.from({ length: 6 }, async () => {
    while (queue.length) {
      const ch = queue.shift(), m = /^(.+) (\d+)$/.exec(ch), p = m && PATHS[m[1]];
      if (!p) continue;
      try {
        const res = await fetch(`https://www.churchofjesuschrist.org/study/api/v3/language-pages/type/content?lang=eng&uri=/scriptures/${p}/${m[2]}`, { headers: { 'User-Agent': 'Mozilla/5.0' } });
        // The page's JSON has raw line breaks in its HTML, so just its audio list is read.
        const a = res.ok && /"audio":(\[[^\]]*\])/.exec(await res.text());
        const got = Object.fromEntries((a ? JSON.parse(a[1]) : [])
          .filter(x => /^(male|female)$/.test(x.variant) && /^https:\/\/[\w.-]+\.churchofjesuschrist\.org\/[\w-]+\.mp3$/.test(x.mediaUrl || ''))
          .map(x => [x.variant, x.mediaUrl]));
        if (Object.keys(got).length) audio[ch] = got;
      } catch (e) { /* no Listen button for it */ }
    }
  }));
  fs.writeFileSync(path.join(ROOT, 'content', 'audio.js'),
    '// Generated by tools/build-reading.mjs at deploy: links to the Church\'s own recordings of each\n' +
    '// chapter (churchofjesuschrist.org), for the Listen button. Do not edit by hand.\n' +
    'window.TU_AUDIO = ' + JSON.stringify(audio) + ';\n');
  const n = Object.keys(audio).length;
  (n < want.length ? console.warn : console.log)(`${n < want.length ? '⚠ ' : ''}content/audio.js: the Church's recordings of ${n} of ${want.length} chapters` + (n < want.length ? ' (the rest have no Listen button)' : ''));
}
